# Generated by Django 5.2.1 on 2025-07-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('designation', models.CharField(choices=[('assistant_professor', 'Assistant Professor'), ('associate_professor', 'Associate Professor'), ('professor_of_practice', 'Professor of Practice')], max_length=50)),
                ('degree', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('year_of_attaining_higher_qualification', models.PositiveIntegerField()),
                ('research_publications', models.PositiveIntegerField(default=0)),
                ('phd_during_the_assessment_year', models.PositiveIntegerField(default=0)),
                ('years_of_teaching_experience', models.PositiveIntegerField(default=0)),
                ('years_as_associate_professor', models.PositiveIntegerField(default=0)),
                ('industry_experience_years', models.FloatField(default=0.0)),
                ('date_of_joining', models.DateField()),
                ('currently_associated', models.BooleanField(default=True)),
                ('date_of_leaving', models.DateField(blank=True, null=True)),
                ('salary', models.FloatField(default=0.0)),
            ],
        ),
    ]
